allowed_patterns:
  - "EXAMPLE_ACCESS_KEY_ID"
  - "EXAMPLE_AWS_REGION"
  - "EXAMPLE_SECRET_ACCESS_KEY"
  - "EXAMPLE_SESSION_TOKEN"
  - "YOUR_AWS_REGION"
  - "YOUR_ACCESS_KEY_ID"
  - "YOUR_SECRET_ACCESS_KEY"
  - "YOUR_SESSION_TOKEN"
  - "EXAMPLE_USER_ID"
  - "FAKE_ARN_123"
  - "SUBSCRIPTION_ID_SUBSCRIPTION_ID"
  - "TENANT_ID_TENANT_ID_TENANT_ID"
  - "SP_APP_ID_SP_APP_ID"
  - "SP_PASSWORD_SP_PASSWORD"
  - "SP_TENANT_SP_TENANT"
  - "AZURE_LOCATION"
  
  
  
  
 
