site_name: Documentation
site_description: Documentation for k0rdent.
site_author: Mirantis, Inc.

docs_dir: docs/
repo_name: GitHub
repo_url: https://..
copyright:
  Copyright &copy; 2025 The k0rdent authors | Documentation distributed under <a href="https://creativecommons.org/licenses/by/4.0/legalcode.txt">CC-BY-4.0</a>.
theme:
  name: "material"
  highlightjs: true
  language: "en"
  custom_dir: docs/custom_theme
  favicon: img/k0s_social.png
  logo: img/k0s_social.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - toc.autohide
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - stylesheets/extra.css
plugins:
  - search

nav:
  - k0rdent: index.md
  - Guide to k0rdent:
    - Guide to k0rdent documentation: guide_to_k0rdent_documentation.md
    - Why k0rdent?: why_k0rdent.md
    - k0rdent architecture: k0rdent_architecture.md
  - QuickStarts and Tutorials:
    - Guide to Quickstarts and Tutorials: guide_to_quickstarts_and_tutorials.md
    - QuickStart 1 - k0rdent pre-requisites: quickstart_1_k0rdent_prerequisites.md
    - QuickStart 2 - AWS infrastructure setup: quickstart_2_aws_infra_setup.md
    - QuickStart 3 - Deploy managed clusters on AWS: quickstart_3_deploy_managed_cluster_aws.md 
  

markdown_extensions:
  - pymdownx.highlight: {}
  - pymdownx.superfences: {}
  - pymdownx.inlinehilite: {}
  - toc:
      permalink: "#"
      toc_depth: 3
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - def_list

extra:
  generator: false

extra:
  generator: false
  version:
    provider: mike
    default: latest
