name: Deploy preview docs from main to next and head

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: pip

      - name: Install mkdocs and dependencies
        run: |
          pip install --upgrade pip
          pip install --disable-pip-version-check -r requirements.txt

      - name: Deploy next and head preview docs from main
        run: |
          git fetch origin gh-pages || echo "gh-pages does not exist yet"
          git checkout gh-pages || git checkout -b gh-pages
          git reset --hard origin/gh-pages || echo "nothing to reset"
          git checkout main
          mike deploy --push next head
          mike alias --push next head
